import { Noto_Sans_JP } from 'next/font/google'
import './globals.css';
import Header from './Header';

// 1. フォントの読み込み
const NotoSansJP = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  preload: true,
});

// 1. ページのメタデータ
export const metadata = {
  title: 'Next.js Note App',
  description: 'Generated by create next app',
}

// 2. ページのレイアウト
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      {/* 3. ページやレイアウトの内容を表示 */}
      <body className={NotoSansJP.className}>
        {/* 7. 共通ヘッダー */}
        <Header></Header>
        {children}</body>
    </html>
  )
}